### ISSUE TITLE
Unable to unselect checkbox after setting val(1)

### ISSUE THREAD

**Issue by ksemsch** [kartik-v/bootstrap-checkbox-x#25]
Hi, 

like the title says I'm not able to unselect a checkbox after selecting it via javascript:

```javascript
// checking it
$( '#option' ).val(1);
$( '#option' ).checkboxX('refresh');
$( '#option' ).trigger('change');
```

The change event is fired twice, which is probably the problem.
Without checking the checkbox via javascript it works like expected. The attribute `data-enclosed-label` is already set to `true`.

Thanks for your help in advance.

**Comment by grandehombre** [comment]
I have the same problem.
It seems to be caused by checkboxX('refresh'). 
Looking in the code (refresh handler, line 151), there is a call to 'init' which causes the problem.
(I have not investigated this any further, as I don't have the time)

So,
- calling refresh stops the control from responding to the mouse click
- it does however respond to the spacebar.

A ***short-term hack*** is to comment out line 151 of checkbox-x-.js.

I must stress that this is a hack!!! I'd rather the author had a look at this

**Comment by kartik-v** [comment]
Seems you are using an outdated release. You need to use the latest release v1.5.4.
